package drivers

import (
	_ "github.com/NewAlist/alist/drivers/115"
	_ "github.com/NewAlist/alist/drivers/115_open"
	_ "github.com/NewAlist/alist/drivers/115_share"
	_ "github.com/NewAlist/alist/drivers/123"
	_ "github.com/NewAlist/alist/drivers/123_link"
	_ "github.com/NewAlist/alist/drivers/123_share"
	_ "github.com/NewAlist/alist/drivers/139"
	_ "github.com/NewAlist/alist/drivers/189"
	_ "github.com/NewAlist/alist/drivers/189pc"
	_ "github.com/NewAlist/alist/drivers/alias"
	_ "github.com/NewAlist/alist/drivers/alist_v2"
	_ "github.com/NewAlist/alist/drivers/alist_v3"
	_ "github.com/NewAlist/alist/drivers/aliyundrive"
	_ "github.com/NewAlist/alist/drivers/aliyundrive_open"
	_ "github.com/NewAlist/alist/drivers/aliyundrive_share"
	_ "github.com/NewAlist/alist/drivers/azure_blob"
	_ "github.com/NewAlist/alist/drivers/baidu_netdisk"
	_ "github.com/NewAlist/alist/drivers/baidu_photo"
	_ "github.com/NewAlist/alist/drivers/baidu_share"
	_ "github.com/NewAlist/alist/drivers/chaoxing"
	_ "github.com/NewAlist/alist/drivers/cloudreve"
	_ "github.com/NewAlist/alist/drivers/cloudreve_v4"
	_ "github.com/NewAlist/alist/drivers/crypt"
	_ "github.com/NewAlist/alist/drivers/doubao"
	_ "github.com/NewAlist/alist/drivers/doubao_share"
	_ "github.com/NewAlist/alist/drivers/dropbox"
	_ "github.com/NewAlist/alist/drivers/febbox"
	_ "github.com/NewAlist/alist/drivers/ftp"
	_ "github.com/NewAlist/alist/drivers/github"
	_ "github.com/NewAlist/alist/drivers/github_releases"
	_ "github.com/NewAlist/alist/drivers/google_drive"
	_ "github.com/NewAlist/alist/drivers/google_photo"
	_ "github.com/NewAlist/alist/drivers/halalcloud"
	_ "github.com/NewAlist/alist/drivers/ilanzou"
	_ "github.com/NewAlist/alist/drivers/ipfs_api"
	_ "github.com/NewAlist/alist/drivers/kodbox"
	_ "github.com/NewAlist/alist/drivers/lanzou"
	_ "github.com/NewAlist/alist/drivers/lenovonas_share"
	_ "github.com/NewAlist/alist/drivers/local"
	_ "github.com/NewAlist/alist/drivers/mediatrack"
	_ "github.com/NewAlist/alist/drivers/mega"
	_ "github.com/NewAlist/alist/drivers/misskey"
	_ "github.com/NewAlist/alist/drivers/mopan"
	_ "github.com/NewAlist/alist/drivers/netease_music"
	_ "github.com/NewAlist/alist/drivers/onedrive"
	_ "github.com/NewAlist/alist/drivers/onedrive_app"
	_ "github.com/NewAlist/alist/drivers/onedrive_sharelink"
	_ "github.com/NewAlist/alist/drivers/pikpak"
	_ "github.com/NewAlist/alist/drivers/pikpak_share"
	_ "github.com/NewAlist/alist/drivers/quark_uc"
	_ "github.com/NewAlist/alist/drivers/quark_uc_tv"
	_ "github.com/NewAlist/alist/drivers/quqi"
	_ "github.com/NewAlist/alist/drivers/s3"
	_ "github.com/NewAlist/alist/drivers/seafile"
	_ "github.com/NewAlist/alist/drivers/sftp"
	_ "github.com/NewAlist/alist/drivers/smb"
	_ "github.com/NewAlist/alist/drivers/teambition"
	_ "github.com/NewAlist/alist/drivers/terabox"
	_ "github.com/NewAlist/alist/drivers/thunder"
	_ "github.com/NewAlist/alist/drivers/thunder_browser"
	_ "github.com/NewAlist/alist/drivers/thunderx"
	_ "github.com/NewAlist/alist/drivers/trainbit"
	_ "github.com/NewAlist/alist/drivers/url_tree"
	_ "github.com/NewAlist/alist/drivers/uss"
	_ "github.com/NewAlist/alist/drivers/virtual"
	_ "github.com/NewAlist/alist/drivers/vtencent"
	_ "github.com/NewAlist/alist/drivers/webdav"
	_ "github.com/NewAlist/alist/drivers/weiyun"
	_ "github.com/NewAlist/alist/drivers/wopan"
	_ "github.com/NewAlist/alist/drivers/yandex_disk"
)

// All do nothing,just for import
// same as _ import
func All() {

}
