name: Sync Alist Release Assets and Create Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  sync-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Checkout NewAlist upstream
        uses: actions/checkout@v4
        with:
          repository: NewAlist/alist
          path: upstream

      - name: Download release assets
        run: |
          mkdir -p root
          cd upstream
          for TAG in $(git tag); do
            mkdir -p "../root/$TAG"
            gh release download "$TAG" --repo NewAlist/alist -D "../root/$TAG"
          done

      - name: Sync assets to my repo
        uses: at-wat/assets-sync-action@v0.6.7
        with:
          repos: ice345/alist
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_user: ice345-bot
          git_email: ice345@example.com
          commit_message: "Sync Alist release assets from NewAlist/alist"
          branch: sync-release-assets
          root_dir: root

      - name: Set tag name
        run: echo "TAG_NAME=v$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          body: Automated release created by GitHub Actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        run: rm -rf root upstream
